<?php

namespace Tests;

use App\Models\Label;
use App\Models\Task;
use App\Models\TodoList;
use App\Models\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Laravel\Sanctum\Sanctum;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @return TodoList
     */
    protected function createTodoList($arg = []): TodoList
    {
        return TodoList::factory()->create($arg);
    }

    /**
     * @return Task
     */
    protected function createTask(TodoList $todoList): Task
    {
        return Task::factory()->create(['todo_list_id' => $todoList->id]);
    }

    /**
     * @return Task
     */
    protected function createTaskAlone(): Task
    {
        return Task::factory()->create();
    }

    protected function createUser(): User
    {
        return User::factory()->create();
    }

    protected function authUser()
    {
        return Sanctum::actingAs($this->createUser());
    }

    protected function createLabel($args = [])
    {
        return Label::factory()->create($args);
    }
}
