<?php

namespace Tests;

use App\Models\Task;
use App\Models\TodoList;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @return TodoList
     */
    protected function createTodoList(): TodoList
    {
        return TodoList::factory()->create();
    }

    /**
     * @return Task
     */
    protected function createTask(TodoList $todoList): Task
    {
        return Task::factory()->create(['todo_list_id' => $todoList->id]);
    }

    /**
     * @return Task
     */
    protected function createTaskAlone(): Task
    {
        return Task::factory()->create();
    }
}
